name: Java CI

# Made by max, modified by me
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30 # Gets the last 20 commits so the changelog might work
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'
      - name: Build with Gradle
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
          FTB_MAVEN_TOKEN: ${{ secrets.FTB_MAVEN_TOKEN}}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish --stacktrace --no-daemon
      - name: Release to CurseForge
        if: |
          github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build curseforge --stacktrace --no-daemon